<a href="https://colab.research.google.com/github/gmpeterson5/SDOH/blob/main/CSCI_8980_Project_GP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files


uploaded = files.upload()

Saving 500_Cities__Local_Data_for_Better_Health__2019_release_20240314.csv to 500_Cities__Local_Data_for_Better_Health__2019_release_20240314.csv


In [5]:
uploaded = files.upload()

Saving SVI_2016_Census_Tracts.csv to SVI_2016_Census_Tracts.csv


In [6]:
import pandas as pd
import numpy as np

places_500_cities = pd.read_csv("500_Cities__Local_Data_for_Better_Health__2019_release_20240314.csv")
places_500_cities.head()

Year StateAbbr   StateDesc   CityName GeographicLevel DataSource  \
0  2017        CA  California  Hawthorne    Census Tract      BRFSS   
1  2017        CA  California  Hawthorne            City      BRFSS   
2  2017        CA  California    Hayward            City      BRFSS   
3  2017        CA  California    Hayward            City      BRFSS   
4  2017        CA  California      Hemet            City      BRFSS   

              Category             UniqueID  \
0      Health Outcomes  0632548-06037602504   
1  Unhealthy Behaviors              0632548   
2      Health Outcomes              0633000   
3  Unhealthy Behaviors              0633000   
4           Prevention              0633182   

                                             Measure Data_Value_Unit  ...  \
0             Arthritis among adults aged >=18 Years               %  ...   
1       Current smoking among adults aged >=18 Years               %  ...   
2  Coronary heart disease among adults aged >=18 ...               %  ...   
3               Obesity among adults aged >=18 Years               %  ...   
4  Cholesterol screening among adults aged >=18 Y...               %  ...   

  High_Confidence_Limit Data_Value_Footnote_Symbol  Data_Value_Footnote  \
0                  15.2                        NaN                  NaN   
1                  15.9                        NaN                  NaN   
2                   4.8                        NaN                  NaN   
3                  24.4                        NaN                  NaN   
4                  78.3                        NaN                  NaN   

   PopulationCount                      GeoLocation CategoryID   MeasureId  \
0             4407   (33.905547923, -118.337332298)    HLTHOUT   ARTHRITIS   
1            84293   (33.914667701, -118.347667728)     UNHBEH    CSMOKING   
2           144186  (37.6329591551, -122.077051051)    HLTHOUT         CHD   
3           144186  (37.6329591551, -122.077051051)     UNHBEH     OBESITY   
4            78657  (33.7352277311, -116.994605005)    PREVENT  CHOLSCREEN   

   CityFIPS     TractFIPS     Short_Question_Text  
0  632548.0  6.037603e+09               Arthritis  
1  632548.0           NaN         Current Smoking  
2  633000.0           NaN  Coronary Heart Disease  
3  633000.0           NaN                 Obesity  
4  633182.0           NaN   Cholesterol Screening  

[5 rows x 24 columns]

In [7]:
ct_500_cities = places_500_cities[places_500_cities['GeographicLevel'] == 'Census Tract']
# ct_500_cities.head()

columns_to_remove = ['StateDesc', 'GeographicLevel', 'DataSource', 'UniqueID', 'Measure', 'Low_Confidence_Limit', 'High_Confidence_Limit', 'GeoLocation', 'CategoryID', 'Short_Question_Text']
ct_500_cities = ct_500_cities.drop(columns=columns_to_remove)
ct_500_cities.head()

# max_values = ct_500_cities.max(axis=0)
# min_values = ct_500_cities.min(axis=0)

# print(max_values)
# print(min_values)

# all_nan = ct_500_cities['Data_Value_Footnote'].unique()
# print(all_nan)


Year StateAbbr    CityName         Category Data_Value_Unit  \
0   2017        CA   Hawthorne  Health Outcomes               %   
5   2017        CA       Indio  Health Outcomes               %   
8   2017        CA   Inglewood  Health Outcomes               %   
15  2016        AL      Hoover       Prevention               %   
18  2017        AL  Huntsville  Health Outcomes               %   

   DataValueTypeID   Data_Value_Type  Data_Value Data_Value_Footnote_Symbol  \
0           CrdPrv  Crude prevalence        14.6                        NaN   
5           CrdPrv  Crude prevalence        22.0                        NaN   
8           CrdPrv  Crude prevalence        12.7                        NaN   
15          CrdPrv  Crude prevalence        81.9                        NaN   
18          CrdPrv  Crude prevalence         9.3                        NaN   

   Data_Value_Footnote  PopulationCount  MeasureId  CityFIPS     TractFIPS  
0                  NaN             4407  ARTHRITIS  632548.0  6.037603e+09  
5                  NaN             5006  ARTHRITIS  636448.0  6.065045e+09  
8                  NaN             2472   DIABETES  636546.0  6.037602e+09  
15                 NaN             1636   MAMMOUSE  135896.0  1.073014e+09  
18                 NaN             4387   DIABETES  137000.0  1.089003e+09

In [8]:
cdc_svi_2016_full = pd.read_csv("SVI_2016_Census_Tracts.csv")
cdc_svi_2016_full.head()

ST    STATE ST_ABBR  STCNTY    COUNTY        FIPS  \
0   1  ALABAMA      AL    1015   Calhoun  1015981902   
1   1  ALABAMA      AL    1097    Mobile  1097990000   
2   1  ALABAMA      AL    1117    Shelby  1117980000   
3   4  ARIZONA      AZ    4012    La Paz  4012980000   
4   4  ARIZONA      AZ    4013  Maricopa  4013980700   

                                        LOCATION   AREA_SQMI  E_TOTPOP  \
0  Census Tract 9819.02, Calhoun County, Alabama   34.644448         0   
1      Census Tract 9900, Mobile County, Alabama    0.000000         0   
2      Census Tract 9800, Shelby County, Alabama   13.634818         0   
3      Census Tract 9800, La Paz County, Arizona  611.591274         0   
4    Census Tract 9807, Maricopa County, Arizona   32.778914         0   

   M_TOTPOP  ...  F_CROWD  F_NOVEH  F_GROUPQ  F_THEME4  F_TOTAL  E_UNINSUR  \
0        11  ...     -999     -999      -999      -999     -999          0   
1        11  ...     -999     -999      -999      -999     -999          0   
2        11  ...     -999     -999      -999      -999     -999          0   
3        12  ...     -999     -999      -999      -999     -999          0   
4        12  ...     -999     -999      -999      -999     -999          0   

   M_UNINSUR  EP_UNINSUR  MP_UNINSUR  E_DAYPOP  
0         11      -999.0      -999.0       335  
1         11      -999.0      -999.0         0  
2         11      -999.0      -999.0       140  
3         12      -999.0      -999.0        11  
4         12      -999.0      -999.0        21  

[5 rows x 124 columns]

In [9]:
columns_to_remove = ['ST', 'STATE', 'ST_ABBR', 'STCNTY', 'COUNTY', 'LOCATION']
cdc_svi_2016 = cdc_svi_2016_full.drop(columns=columns_to_remove)
cdc_svi_2016 = cdc_svi_2016[cdc_svi_2016['E_TOTPOP'] != 0] ## Removing rows where the E_TOTPOP = 0

# from sklearn.impute import SimpleImputer

# impmean = SimpleImputer(missing_values=-999, strategy='median')
# cdc_svi_2016_imputed = impmean.fit_transform(cdc_svi_2016)

# cdc_svi_2016_imputed = pd.DataFrame(cdc_svi_2016_imputed, columns=cdc_svi_2016.columns)

In [10]:
ct_500_cities.loc[:, ['TractFIPS', 'Data_Value']]

TractFIPS  Data_Value
0       6.037603e+09        14.6
5       6.065045e+09        22.0
8       6.037602e+09        12.7
15      1.073014e+09        81.9
18      1.089003e+09         9.3
...              ...         ...
810098  5.502500e+10         3.8
810099  5.305306e+10        74.2
810100  5.301104e+10        28.1
810101  5.508701e+10        27.0
810102  5.305307e+10        78.6

[782047 rows x 2 columns]

In [11]:
merged = pd.merge(ct_500_cities.loc[:, ['MeasureId', 'TractFIPS', 'Data_Value']], cdc_svi_2016, left_on=['TractFIPS'], right_on=['FIPS'], how='inner')
# merged_imputed = pd.merge(ct_500_cities.loc[:, ['MeasureId', 'TractFIPS', 'Data_Value']], cdc_svi_2016_imputed, left_on=['TractFIPS'], right_on=['FIPS'], how='inner')
merged.head()

MeasureId     TractFIPS  Data_Value        FIPS  AREA_SQMI  E_TOTPOP  \
0  ARTHRITIS  6.037603e+09        14.6  6037602504   0.124112      4528   
1        CHD  6.037603e+09         3.7  6037602504   0.124112      4528   
2     KIDNEY  6.037603e+09         2.8  6037602504   0.124112      4528   
3      SLEEP  6.037603e+09        41.8  6037602504   0.124112      4528   
4       COPD  6.037603e+09         4.5  6037602504   0.124112      4528   

   M_TOTPOP  E_HU  M_HU  E_HH  ...  F_CROWD  F_NOVEH  F_GROUPQ  F_THEME4  \
0       343  1851    52  1740  ...        1        0         0         2   
1       343  1851    52  1740  ...        1        0         0         2   
2       343  1851    52  1740  ...        1        0         0         2   
3       343  1851    52  1740  ...        1        0         0         2   
4       343  1851    52  1740  ...        1        0         0         2   

   F_TOTAL  E_UNINSUR  M_UNINSUR  EP_UNINSUR  MP_UNINSUR  E_DAYPOP  
0        4        975        191        21.6         4.2      1206  
1        4        975        191        21.6         4.2      1206  
2        4        975        191        21.6         4.2      1206  
3        4        975        191        21.6         4.2      1206  
4        4        975        191        21.6         4.2      1206  

[5 rows x 121 columns]

In [16]:
diabetes = merged[merged['MeasureId'] == 'DIABETES'].dropna(subset=['Data_Value'])
# diabetes_imputed = merged_imputed[merged_imputed['MeasureId'] == 'DIABETES'].dropna(subset=['Data_Value'])
# diabetes.head()

print(diabetes['Data_Value'].describe())

count    27204.000000
mean        10.810385
std          4.268557
min          0.800000
25%          7.900000
50%         10.000000
75%         12.900000
max         39.500000
Name: Data_Value, dtype: float64


In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# X = diabetes.loc[:, diabetes.columns != 'Data_Value']
y = diabetes['Data_Value']
# y_imputed = diabetes_imputed['Data_Value']

# X_numeric = X.select_dtypes(include='number')
columns_to_remove = ['Data_Value', 'TractFIPS', 'FIPS', 'F_TOTAL'] #, 'RPL_THEMES', 'SPL_THEMES', 'F_THEME1', 'RPL_THEME1', 'SPL_THEME1', 'F_THEME2', 'RPL_THEME2', 'SPL_THEME2', 'F_THEME3', 'RPL_THEME3', 'SPL_THEME3', 'F_THEME4', 'RPL_THEME4', 'SPL_THEME4']
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if 'THEME' in col]
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if col.startswith('E_')]
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if col.startswith('M_')]
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if col.startswith('EPL_')]
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if col.startswith('MP_')]
columns_to_remove = columns_to_remove + [col for col in diabetes.columns if col.startswith('F_')]

X_numeric = diabetes.select_dtypes(include='number').drop(columns=columns_to_remove)
X_numeric_scaled = scaler.fit_transform(X_numeric)

linear_reg = LinearRegression().fit(X_numeric_scaled,y)
# X_numeric.head()
# columns_to_remove

# X_numeric_imputed = diabetes_imputed.select_dtypes(include='number').drop(columns=columns_to_remove)
# X_numeric_scaled_imputed = scaler.fit_transform(X_numeric_imputed)

# linear_reg_imputed = LinearRegression().fit(X_numeric_scaled_imputed,y)
# X_numeric_imputed.head()

In [18]:
linear_reg.score(X_numeric_scaled,y)

0.7226819684103579

In [19]:
# linear_reg.score(X_numeric_scaled_imputed,y)

0.6235285326600208

In [20]:
linear_reg.coef_

array([ 0.00486347,  0.60487269,  0.07448471, -0.99914018,  1.08779371,
        1.88092442,  0.38135959,  0.34055135,  0.44181374,  2.08382368,
       -0.54039993, -0.20520922, -1.34238994, -0.65096382,  0.91460032,
       -0.22740579, -0.53299089])

In [21]:
# abs(linear_reg.coef_)

array([0.00486347, 0.60487269, 0.07448471, 0.99914018, 1.08779371,
       1.88092442, 0.38135959, 0.34055135, 0.44181374, 2.08382368,
       0.54039993, 0.20520922, 1.34238994, 0.65096382, 0.91460032,
       0.22740579, 0.53299089])

In [22]:
sorted_indexes = np.argsort(linear_reg.coef_)
sorted_indexes

array([12,  3, 13, 10, 16, 15, 11,  0,  2,  7,  6,  8,  1, 14,  4,  5,  9])

In [23]:
sorted_headers = [X_numeric.columns[index] for index in sorted_indexes]
sorted_headers

['EP_MOBILE',
 'EP_PCI',
 'EP_CROWD',
 'EP_LIMENG',
 'EP_UNINSUR',
 'EP_GROUPQ',
 'EP_MUNIT',
 'AREA_SQMI',
 'EP_UNEMP',
 'EP_DISABL',
 'EP_AGE17',
 'EP_SNGPNT',
 'EP_POV',
 'EP_NOVEH',
 'EP_NOHSDP',
 'EP_AGE65',
 'EP_MINRTY']

In [24]:
diabetes_desc = diabetes['Data_Value'].describe()
bin_edges = [diabetes_desc[3], diabetes_desc[4], diabetes_desc[6], diabetes_desc[7]]
bin_labels = ['low', 'medium', 'high']

y_binned = pd.cut(y, bins=bin_edges, labels=bin_labels, include_lowest=True)

print(y_binned)


23        medium
49        medium
56        medium
88        medium
94           low
           ...  
780057       low
780089      high
780112    medium
780119    medium
780149       low
Name: Data_Value, Length: 27204, dtype: category
Categories (3, object): ['low' < 'medium' < 'high']


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.model_selection import cross_validate
import matplotlib.pyplot as plt

X_rf = X_numeric_scaled
# X_rf_2 = X_projected[:, 0:25]
num_trees = [1, 50, 100, 200, 300, 500] # [1, 50, 100, 200, 300, 500, 1000]
m =  X_rf.shape[1]
# m_2 = X_rf_2.shape[1]
max_features = [ m, m//2, 'sqrt']
test_accs = []

# Create StratifiedKFold validation
n_splits = 10
skf = StratifiedKFold(n_splits=n_splits, shuffle=True)

for features in max_features:
    for tree in num_trees:
        # Instantiate a random forest object. Set max_depth=5.
        # rf_clf = RandomForestClassifier(n_estimators=tree, max_features=features, max_depth=5)
        rf_clf = RandomForestClassifier(n_estimators=tree, max_features=features, max_depth=10)

        # Perform cross validation
        rf_cv = cross_validate(rf_clf, X_rf, y_binned, scoring='accuracy', cv=skf, return_estimator=True)

        # Record the mean of CV test scores

        test_accs.append(np.mean(rf_cv['test_score']))


# print(test_accs)
# print(test_accs[1])

plt.xlabel('Number of Trees')
plt.ylabel('CV test accuracy')
for i, max_feat in enumerate(max_features):
    plt.plot(num_trees, test_accs[i*len(num_trees):(i*len(num_trees))+len(num_trees)], label="max_features = "+str(max_feat))
plt.legend(loc="lower right")

plt.show()